try:
    print(param)

# 오류가 발생한 변수이름을 알려줌
except Exception as e:
    print(e)
